[pytest]
minversion = 7.0
testpaths =
    "stixpy"
    "docs"
norecursedirs =
    ".*"
    ".tox"
    "build"
    "docs/_build"
    "docs/generated"
    "*.egg-info"
    "examples"
    "stixpy/_dev"
    ".jupyter"
    ".history"
    "tools"
doctest_plus = enabled
doctest_optionflags =
    NORMALIZE_WHITESPACE
    FLOAT_CMP
    ELLIPSIS
text_file_format = rst
addopts =
    --doctest-rst
    -p no:unraisableexception
    -p no:threadexception
remote_data_strict = True
filterwarnings =
    # Turn all warnings into errors so they do not pass silently.
    error
    # Do not fail on pytest config issues (i.e. missing plugins) but do show them
    always::pytest.PytestConfigWarning
    # A list of warnings to ignore follows. If you add to this list, you MUST
    # add a comment or ideally a link to an issue that explains why the warning
    # is being ignored
    ignore:defusedxml.lxml is no longer supported:DeprecationWarning
    ignore:Matplotlib is currently using agg:UserWarning
    ignore: Python 3.14 will, by default, filter extracted tar archives and reject:DeprecationWarning
    ignore:Use `durations` instead:DeprecationWarning
    ignore:unclosed event loop:ResourceWarning:
    ignore:SAS solution not available using spacecraft pointing:UserWarning
    ignore:No good SAS solution found for time range:UserWarning
    ignore:Data has no positive values:UserWarning
    ignore:Using \.data to access:UserWarning
    ignore:FigureCanvasAgg is non-interactive:UserWarning
    ignore:Invalid 'BLANK' keyword:astropy.io.fits.verify.VerifyWarning
    ignore::pyparsing.warnings.PyparsingDeprecationWarning
    ignore:Using 'generic' unit for NumPy timedelta:DeprecationWarning
    ignore::erfa.ErfaWarning
